version: '3.6'
services:
    traefik:
        build: .
        ports:
            - "80:80"
            - "443:443"
            - "8080:8080"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./acme-data:/acme-data
        networks:
            - traefik
networks:
    traefik:
        name: traefik
