version: '3.6'
services:
    traefik:
        image: traefik
        command: --web --docker --docker.watch --entryPoints="Name:https Address::443 TLS:/certs/cert.pem,/certs/key.pem" --entryPoints="Name:http Address::80 Redirect.EntryPoint:https"
        ports:
            - "80:80"
            - "443:443"
            - "8080:8080"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /dev/null:/traefik.toml
            - ./certs:/certs
        network_mode: bridge
#
# Example service:
#     example:
#         image: nginx
#         network_mode: bridge
#         labels:
#             - "traefik.frontend.rule=Host:nginx.traefik.xsika.cz"
#             - "traefik.port=80"
#             - "traefix.port=443"
#             - "traefik.frontend.entryPoints=http,https"

